import { DNS } from '@/stores/dnsStore';

// Prefixed with `system--` to avoid conflicts with user-defined DNS servers
export const dnsServers: DNS[] = [
  {
    id: 'system--opendns',
    name: 'OpenDNS',
    ip: '208.67.222.220',
    country: 'United States',
    city: 'San Francisco',
  },
  {
    id: 'system--google',
    name: 'Google',
    ip: '8.8.8.8',
    country: 'United States',
    city: 'Mountain View',
  },
  {
    id: 'system--quad9',
    name: 'Quad9',
    ip: '9.9.9.9',
    country: 'United States',
    city: 'Berkeley',
  },
  {
    id: 'system--probe-networks',
    name: 'Probe Networks',
    ip: '82.96.64.2',
    country: 'Germany',
    city: 'Saarland',
  },
  {
    id: 'system--4d-data-centres',
    name: '4D Data Centres Ltd',
    ip: '37.209.219.30',
    country: 'United Kingdom',
    city: 'Byfleet',
  },
  {
    id: 'system--oskar-emmenegger',
    name: 'Oskar Emmenegger',
    ip: '194.209.157.109',
    country: 'Switzerland',
    city: 'Zizers',
  },
  {
    id: 'system--nemox',
    name: 'nemox.net',
    ip: '83.137.41.9',
    country: 'Austria',
    city: 'Innsbruck',
  },
  {
    id: 'system--at-and-t-services',
    name: 'AT&T Services',
    ip: '12.121.117.201',
    country: 'United States',
    city: 'Miami',
  },
  {
    id: 'system--verisign-global-registry-services',
    name: 'VeriSign Global Registry Services',
    ip: '64.6.64.6',
    country: 'United States',
    city: 'Virginia',
  },
  {
    id: 'system--quad9-sf',
    name: 'Quad9',
    ip: '149.112.112.112',
    country: 'United States',
    city: 'San Francisco',
  },
  {
    id: 'system--centurylink',
    name: 'CenturyLink',
    ip: '205.171.202.66',
    country: 'United States',
    city: '',
  },
  {
    id: 'system--fortinet-inc',
    name: 'Fortinet Inc',
    ip: '208.91.112.53',
    country: 'Canada',
    city: 'Burnaby',
  },
  {
    id: 'system--skydns',
    name: 'Skydns',
    ip: '195.46.39.39',
    country: 'Russia',
    city: 'Yekaterinburg',
  },
  {
    id: 'system--liquid-telecommunications-ltd',
    name: 'Liquid Telecommunications Ltd',
    ip: '5.11.11.5',
    country: 'South Africa',
    city: 'Cullinan',
  },
  {
    id: 'system--pyton-communication-services-b-v',
    name: 'Pyton Communication Services B.V.',
    ip: '193.58.204.59',
    country: 'Netherlands',
    city: 'Weert',
  },
  {
    id: 'system--association-gitoyen',
    name: 'Association Gitoyen',
    ip: '80.67.169.40',
    country: 'France',
    city: 'Paris',
  },
  {
    id: 'system--prioritytelecom-spain-s-a',
    name: 'Prioritytelecom Spain S.A.',
    ip: '212.230.255.1',
    country: 'Spain',
    city: 'Madrid',
  },
];
export type DnsServer = (typeof dnsServers)[number];
